### ISSUE TITLE
Add CocoaPods to the project

### ISSUE THREAD

**Issue by olebedev** [doomsower/react-native-vkontakte-login#1]
Is there any how-to description?

**Comment by doomsower** [comment]
You can follow steps 2 throught 7 of [this](https://blog.callstack.io/login-users-with-facebook-in-react-native-4b230b847899#.lai35aq3a) tutorial.
Also check out example project.

**Comment by olebedev** [comment]
Thanks!

**Comment by olebedev** [comment]
That link is not working for me. I spend a lot of hours for testing and organizing the project with CocoaPods, following the link above. But, I have no result for now... So, disappointing

**Comment by olebedev** [comment]
So strange, I have reduced pod react's dependencies down to four:
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]
```
and it works now. 

Thanks a lot.
