### ISSUE TITLE
Couldn't build ver. 0.1.8 on Android

### ISSUE THREAD

**Issue by vladbars** [doomsower/react-native-vkontakte-login#10]
To fix it I just changed in VKAuthModule.java:
**public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data)** 
to
**public void onActivityResult( int requestCode, int resultCode, Intent data)**

**Comment by doomsower** [comment]
This change was introduced in version 0.1.8 of this module to support React-Native 0.33+. If you use React-Native 0.32 or older, use version 0.1.7 of this package.
