### ISSUE TITLE
[iOS] Crash on app initialization.

### ISSUE THREAD

**Issue by frmrgr** [doomsower/react-native-vkontakte-login#11]
I have react-native 0.35, xcode 8. When app is built on iOS 10 simulator, the following error occurs:

    [NSCFString stringValue]: unrecognized selector sent to instance XXXXXXXX

for the following line of code (`ios/VkontakteManager.m`):

    sdk = [VKSdk initializeWithAppId:[appId stringValue]];

Changing the line to

    sdk = [VKSdk initializeWithAppId:(NSString *) appId];

allows the app to work and use vk authorization. Unfortunately, I don't know objective C at all, so I don't understand what those lines do and how that problem should be fixed properly.

**Comment by doomsower** [comment]
The problem is that you pass vk app id as string and not as number.
I was able to reproduce this error by commenting out `VKLogin.initialize` calls in JS, and setting string VK_APP_ID value in Info.plist.
How do you pass id?

**Comment by frmrgr** [comment]
Alright, I have really read the manual as that this value should be string. Don't know how that happened, sorry for bother.
