### ISSUE TITLE
impossible to share cyrrilic url

### ISSUE THREAD

**Issue by karpoff** [doomsower/react-native-vkontakte-login#13]
Hi,

it is impossible to share cyrrilic link (for example http://яндекс.рф)
VKLogin.share returns "share url is incorrect" error
is there any way to do this (I know that I can replace it by not user-frienly latin url like http://xn--d1acpjx3f.xn--p1ai but it will be shown in vk)?

also I have to specify linkText and description here. Is there any way to load this info from meta tags of shared url like it does while sharing from vk?

**Comment by 4031651** [comment]
This module does not process link url, just pass it to VKShareDialogController. Maybe you should address this question to vk sdk repo https://github.com/VKCOM/vk-ios-sdk/issues.
