### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by joinjoohny** [doomsower/react-native-vkontakte-login#15]
I have an error, any idea? Thx
/node_modules/react-native-vkontakte-login/ios/VkontakteSharing.m:3:9:

error: 'RCTUtils.h' f
File not found with <angled> include; use "quotes" instead
#import <RCTUtils.h>
        ^~~~~~~~~~~~
        "RCTUtils.h"

** BUILD FAILED **

**Comment by 4031651** [comment]
Hi. After [e1577df](https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d), Native code on iOS must refer to headers out of the react namespace. So, you should replace
```c
#import "RCTUtils.h"
```
with
```c
#import <React/RCTUtils.h>
```
I'll fix it tommorow.

**Comment by doomsower** [comment]
Yes, this is 0.40 breaking changes. I'm currently traveling and I don't have xcode around. But I can merge PR!

**Comment by 4031651** [comment]
Fixed in #17
