### ISSUE TITLE
Invalid type in JSON write (VKError)

### ISSUE THREAD

**Issue by joinjoohny** [doomsower/react-native-vkontakte-login#16]
Hello.
There is an error, if user push on done button or cancel, when he wants auth with vk.
Maybe incorrect processing error.

`RCTJSONStringify() encountered the following error: Invalid type in JSON write (VKError)`

Thx!

**Comment by doomsower** [comment]
I'll check this when I return from my travel. Which version of React Native are you using?

**Comment by joinjoohny** [comment]
React-native 0.39.0

**Comment by webzepter** [comment]
@doomsower any updates?

**Comment by doomsower** [comment]
I've just published new version of this package, it requires react-native 0.41. This version should handle errors better.
Please tell me if you still have this bug in new version. If so, does it happen in example project too?

P.S. Можно по-русски, конечно.

**Comment by doomsower** [comment]
Fixed, see more discussion in #21
