### ISSUE TITLE
works for RN 0.42 ?

### ISSUE THREAD

**Issue by tadjik1** [doomsower/react-native-vkontakte-login#20]
Hi there, thanks a lot for your work!

I'm trying to repeat all the installation steps (in that [article](https://blog.callstack.io/login-users-with-facebook-in-react-native-4b230b847899#.lai35aq3a) as well) for newest 0.42 RN and got a lot of errors.

Did you test this library for newest version of RN and is it possible that some steps in instructions are outdated?

**Comment by doomsower** [comment]
I didn't test it with 0.42. Will be able to upgrade it after 20th. 

Konstantin Kuznetsov

**Comment by tadjik1** [comment]
@doomsower thanks!

what I did: just get empty project (after `react-native init`), and apply each steps of your instruction.
I've received a lot of erros during this process, but finally what I cann't resolve - is: `Native module cannot be null`

<img width="375" alt="screen shot 2017-03-12 at 12 43 54" src="https://cloud.githubusercontent.com/assets/1452895/23831451/b06146dc-0721-11e7-87f0-eaf1c4a19b10.png">

I even didn't change source files, for example Jest tests are passed:
```
➜  ... npm test

> ...
> jest

 PASS  __tests__/index.ios.js
 PASS  __tests__/index.android.js

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.594s, estimated 8s
Ran all test suites.
```

**Comment by sizovilya** [comment]
I have the same problem on ios on RN 0.10.41. 
Android works fine.

**Comment by doomsower** [comment]
@tadjik1 so to test this I just created new project and followed the steps from readme, and it worked for me. I used pod configuration that you provided (I assume that it's just part of your Podfile and not its entire content). Can you share a repo with this minimal not working project?

**Comment by tadjik1** [comment]
@doomsower I'll try to split my project and extract minimal required example.
thanks a lot for your testing.

btw: what's the reason to do all this things with pods and removing linked libraries? I don't know anything about iOs development without RN, that's why I'm asking. And if I will need to connect another native library should I repeat steps from this instruction as well?

**Comment by 4031651** [comment]
Pods - it's easy way to manage dependencies. Like gradle for android. No necessary to remove linked deps from project and use pods. Readme describe how to use this module w/o pods.

**Comment by doomsower** [comment]
@tadjik1 Cocoapods is a package manager for native ios code, just like npm for javascript. Some other native modules support it, for others you'll have to add their native code and native dependencies (like native VK or FB SDK) manually via xcode.

**Comment by tadjik1** [comment]
@doomsower @4031651 during splitting up my project and extracting simple example it starts working magically :)

thanks a lot for your help and for your beautiful library!
