### ISSUE TITLE
Не получается авторизироваться.

### ISSUE THREAD

**Issue by bintoll** [doomsower/react-native-vkontakte-login#21]
Все устанавливал по мануалу без cocoapods. После нажатия кнопки залогинится открывается вебвью, когда нажимаю разрешить, происходит микро загрузка чего-то и все, ничего не меняется. Т.е. залогиниться должно было, но почему-то нет и само не закрылось. Тгда нажимаю Done и вижу 
![image](https://cloud.githubusercontent.com/assets/20185572/24774183/acdc72a8-1b20-11e7-90d4-68992a791da1.png)
Но стоит заметить что этот красный экран всплывает только если включен дебаггер, если его отключить, то приложение выводит на главный экран, но человек по прежнему не залогинен.
еще кидает вот такую ошибку -canOpenURL: failed for URL: "vkauthorize://authorize" - error: "The operation , но я так понял, что это потому что на симуляторе нет приложения vk

**Comment by doomsower** [comment]
Какая версия react-native? И можно фрагмент кода с инициализацией и логином?

**Comment by bintoll** [comment]
Ого как оперативно.
Версии:
react-native-cli: 2.0.1
react-native: 0.42.3
![image](https://cloud.githubusercontent.com/assets/20185572/24774409/7705b62a-1b21-11e7-8ad4-602413e253c8.png)
иннициализация происходет в componentWillMount - VKLogin.initialize(5968745);

**Comment by doomsower** [comment]
Я кажется исправил эту ошибку, но до конца не уверен, что именно эту.
Можешь попробовать собрать с версией из ветки `rctjsonstringify`?

**Comment by bintoll** [comment]
Ошибка с красным экраном исчезла. Однако все равно не удается залогиниться(

**Comment by doomsower** [comment]
Не совсем понял, что имеется в виду? Четвертый пункт из установки с cocoapods?

**Comment by bintoll** [comment]
Ага, пункт из установки с cocoapods так же должен быть применен если человек устанавливает без cocoapods
