### ISSUE TITLE
Pod: React has been deprecated! Duplicate module name: react-native-packager

### ISSUE THREAD

**Issue by Dictory** [doomsower/react-native-vkontakte-login#22]
Hello.
Now i have error: React has been deprecated!
Pod install `React (0.11.0)` (Why?)
If run `react-native run-ios` i get next errors:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /apps/MyApp/ios/Pods/React/packager/package.json collides with /apps/MyApp/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /apps/MyApp/ios/Pods/React/packager/package.json collides with /apps/MyApp/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (//apps/MyApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/apps/MyApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
``` 

react: "15.6.1"
react-native: "0.38.1"
react-native-vkontakte-login: "^0.1.16"

**Comment by Dictory** [comment]
Thanks for answer.
I doesn\`t have react in my Podfile
[It is from react-native-vkontakte-login.podspec](https://github.com/doomsower/react-native-vkontakte-login/blob/master/react-native-vkontakte-login.podspec#L15)
About react-native version: i can\`t upgrade because after 0.38.1 android has low fps and that now without answer =)

**Comment by doomsower** [comment]
This line is required, because `react-native-vkontakte-login` depends on react. If you install with cocoapods and not manually, cocoapods will need to resolve `React` dependency. However, `React` pod is deprecated from global pods repository and is distributed within `react-native` npm package. In `react-native-vkontakte-login` podspec I cannot specify dependency to `React` pod from node_modules because `react-native-vkontakte-login` is a library and I can't know in advance where node_modules will be in a project that uses `react-native-vkontakte-login`. That's why you have to override `React` pod in Podfile of your project, like I wrote in previous message.

P.S. Если не очень понятно, можно на русском продолжить

**Comment by Dictory** [comment]
Ok i understand. 
Just override `React` pod;

-----------------------------
Не очень красиво обсуждать вопрос не на интернациональном языке, если кто-то столкнется с данной проблемой - сразу сможет понять как ее решить )
А вообще, я все же не могу понять, зачем зависимость в Podfile? Да, `react-native-vkontakte-login` - это библиотека, но вряд ли она будет использована отдельно от `react-native` т.к. написана под нее. В любом случае React будет в зависимостях.
По-моему, легче указать в readme, что при отсутствии зависимости необходимо добавить библиотеку. Да и почему именно через Pod? Почему не просто зависимостью через pakages?
P.S. Спасибо за библиотеку.

**Comment by doomsower** [comment]
`react-native-vkontakte-login` зависит от `react` и от `vk-ios-sdk`. Первое всегда есть, да, второго нет. Я согласен, что cocoapods - это не очень удобно для react-native проекта, и планирую от этого избавиться, но ручная инсталляция с залазаньем в xcode меня вообще не устраивает, так что пока что cocoapods - самое простое автоматическое решение. Дальше типа мысли вслух, что я планирую рассмотреть и как от него избавиться
1. Для проекта с `react-native-vkontakte-login` нужна транзитивная зависимость `vk-ios-sdk`, как же я могу из `react-native-vkontakte-login` ей управлять?
2. Сейчас она указана в podspec - проект с cocoapods автоматически скачивает из репозитория последнюю версию `vk-ios-sdk` и все линкует
3. Без cocoapods у меня есть следующие вариант
  3.1. Тупо включить файлы из `vk-ios-sdk` в репозиторий `react-native-vkontakte-login` - но тогда зафиксируется версия
  3.2. Попробовать git submodule - но эта идея мне не нравится, при публикации в npm все равно версия зафиксируется
  3.3. Добавить npm postinstall script, который скачает последнюю версию сам
  3.4. Попробовать заставить npm как-то скачивать `vk-ios-sdk`, но скорее всего это невозможно, т.к. там нет package.json
4. После этого нужно как-то залинковать `react-native-vkontakte-login` и `vk-ios-sdk` в xcode проект. Мне кажется, для этого достаточно будет для первого создать `.xcodeproj`, а дальше `react-native link` тупо утаскивает из npm модуля все `.xcodeproj` и добавляет их в проект, но это надо проверять

Если я что-то упускаю или есть какие мысли на этот счет - буду рад услышать.

В идеале `react-native link` должно быть единственной необходимой командой, дальше она в интерактивном режиме спрашивать VK APP ID и дальше править android manifest, в ios проект добавлять CFBundleURLTypes, вот это все.

Сейчас на это нет времени, но скоро буду добавть вход через вк к новому проекту, тогда видимо попытаюсь все это попробовать.

**Comment by Dictory** [comment]
Так нет, это все понятно и от pod уйти сложно.
submodule - вообще не вариант.
Я не пойму, зачем в pod зависимость React? Оставить там `vk-ios-sdk` и все, а ставить их через Pod легко. Т.е. что-то типа:
Add to Podfile:
`pod "VK-ios-sdk" `
Разве этого недостаточно?

**Comment by doomsower** [comment]
Наверное достаточно, `react-native-maps` так и работает. Надо попробовать

**Comment by Dictory** [comment]
Можно еще вариант с [Carthage](https://github.com/Carthage/Carthage)

--------------------------
Только для iOS 8 и выше 

Добавьте в Ваш Cartfile следующее:
`github "VKCOM/vk-ios-sdk" >= 1.3.8`

Инструкции по сборке Carthage Вы можете найти [здесь](https://github.com/Carthage/Carthage#if-youre-building-for-ios). 

Затем импортируйте главный заголовочный файл:
`#import <VKSdkFramework/VKSdkFramework.h>`

**Comment by doomsower** [comment]
Думаю, это плохая идея. Cocoapods часто встречается в разных react-native модулях и с некоторой вероятностью он уже будет в проекте, а вот Carthage я не встречал.

**Comment by Dictory** [comment]
Согласен, но если есть Cocoapods пусть, есть без него, почему бы не добавить в описание альтернативный путь?

**Comment by doomsower** [comment]
Чтобы это добавить в описание мне нужно попробовать поставить все через Carthage, чтобы убедиться, что это работает. На это у меня нет ни времени, ни желания. Есть описание ручной установки без Cocoapods уже.

**Comment by Dictory** [comment]
Хорошо
