### ISSUE TITLE
Archive build failed after adding a pod 

### ISSUE THREAD

**Issue by tavriaforever** [doomsower/react-native-vkontakte-login#28]
Hi! Thanks for you module!
I follow all instruction to install module and everything works perfect. But now I get an error when I try to archive build in iOS for upload to TestFlight.

react-native 0.45.1
```
    /Users/tavria/Library/Developer/Xcode/DerivedData/myapp-hfmnmtfftxluofdugtpjdhghbwxu/Build/Intermediates/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/libReact.a(RCTHTTPRequestHandler.o)
    /Users/tavria/Library/Developer/Xcode/DerivedData/myapp-hfmnmtfftxluofdugtpjdhghbwxu/Build/Intermediates/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/libRCTNetwork.a(RCTHTTPRequestHandler.o)
ld: 99 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I understand that this problem about duplicate react code into project Library and react code into Pod. But if I delete it from project library – modules that was install without pod, like fbsdk, they will crash. If I remove react from Podfile – I have a lot of errors like 

![rctdevsettings mm 2017-08-14 11-25-23](https://user-images.githubusercontent.com/975906/29263830-50f445b4-80e3-11e7-917e-b66481269344.png)

I try to add jschelpers to project -> build phases -> link binary with libraries – but this is not helped me) 

Very interesting fact, when I build debug or release build everything builded

**Comment by doomsower** [comment]
Please show your `Podfile` which causes conflicts. What error do you get when non-cocoapods modules cause app crash?

**Comment by tavriaforever** [comment]
PodFile 
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'palmy_mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for palmy_mobile
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'BatchedBridge',
    'RCTImage',
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-vkontakte-login', :path => '../node_modules/react-native-vkontakte-login'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'palmy_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

If I delete `RCTNetwork` and `RCTImage` from there 

![palmy_mobile xcodeproj 2017-08-14 11-47-49](https://user-images.githubusercontent.com/975906/29264625-7c4d604e-80e6-11e7-94ab-0e6350ed28fb.png)

Archive build complete, but when app starte I got an exception in facebook sdk

![rctnativemodule mm 2017-08-14 14-06-34](https://user-images.githubusercontent.com/975906/29269390-db8d8d64-80f9-11e7-8f49-81c63517ea0f.png)

All code from this facebook native module here https://gist.github.com/tavriaforever/bdc720682c16cf523f61b19cecb35eec

Maybe I should add something to pod

**Comment by doomsower** [comment]
If you delete something from `Libraries` then you should have it installed via Cocoapods. With this `Podfile`, you can delete `RCTImage`, but if you want to delete `RCTNetwork` you have to add it to `Podfile`.

**Comment by tavriaforever** [comment]
Yes, I understand it, but I add `RCTNetwork` to pod file, go to myproject/ios and run `pod install`. After that archive will build, but app doesn`t start with fb crash

**Comment by doomsower** [comment]
From these screenshots I cannot get fbsdk error, they show some js<->native bridge stacktrace. Maybe the problem is with fbsdk.
I suggest you to try this:
1) Clear project derived data - this can help with archive build if you mess with dependencies a lot
2) If this doesn't help - try to install fbsdk with cocoapods
3) As a last resort, revert all commits with `react-native-vkontakte-login` cocoapods installation and install it manually

**Comment by tavriaforever** [comment]
Thanks a lot! I choose third variant and deactivate cocoapod at all and install everything without. Now everything works! Thanks!
