### ISSUE TITLE
[Android] Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by olebedev** [doomsower/react-native-vkontakte-login#3]
Yet another error with android. Maybe I missing something at installation step?

The code is quite simple:
```javascript
export function authorize() {
  // VKLogin.initialize('...')
  return VKLogin.login(['email'])
}
```
Vk app id setup in settings. But with `VKLogin.initialize('...')` have same error.
![Error](https://infinit.io/_/5ybkJee.png)

Thanks in advance.

**Comment by doomsower** [comment]
Seems that in react-native 0.29 `react-native link` ask `rnpm link` got broken.
I've updated readme with  instructions

**Comment by olebedev** [comment]
Thanks!
