### ISSUE TITLE
IOS Allow button doesn't work

### ISSUE THREAD

**Issue by yuoppp** [doomsower/react-native-vkontakte-login#32]
![2018-01-31 14 11 36](https://user-images.githubusercontent.com/31764980/35619993-c0979640-0690-11e8-9097-85ca3faa16c7.png)

Allow and Cancel buttons don't work. Nothing happens when I press them.

RN: 0.52.2
react: 16.2.0
react-native-vkontakte-login: 0.3.18

**Comment by doomsower** [comment]
It seems that LSApplicationQueriesSchemes/CFBundleTypeRole do not work. Or VK application was not configured for your bundle id.  
How did you install the module?  
Is Android version working?

**Comment by yuoppp** [comment]
Android works fine. 

Installed manually using this tutorial: https://github.com/doomsower/react-native-vkontakte-login/blob/master/docs/installation.md

I'll double check my Query Schemes and VK Application Settings in an hour and report here.

p.s.

When I press "Done" in the top left corner when getting stuck in the "Allow-Cancel" window the app crashes with an exception.

p.s.

![2018-01-31 15 03 42](https://user-images.githubusercontent.com/31764980/35622183-f9a3a92c-0697-11e8-88ac-6f1b83d1f034.png)

**Comment by yuoppp** [comment]
Okay, I figured out what was the problem.

It is my bad.  Because of i had multiple packages, which use 
`- (BOOL)application:(UIApplication *)application openURL:`
method I just skipped by mistake the step where I should add `[VKSdk processOpenURL:url fromApplication:sourceApplication];` 

Now everything works fine. 

Thank you for replying fast.
