### ISSUE TITLE
Sharing by non auth user

### ISSUE THREAD

**Issue by 4external** [doomsower/react-native-vkontakte-login#34]
Hi!

I think that code not need.
  ```
if (![sdk hasPermissions:permissions]){
    //reject(RCTErrorUnspecified, nil, RCTErrorWithMessage(@"Access denied: no access to call this method"));
    //return;
  }
```
Because VK-nonauthed user cannot sharing info.
When i commented reject and return i see prompt that i not authed, than authed and can share info.

**Comment by doomsower** [comment]
This is not about user being authenticated or not, this is about wall post permissions. You should track authentication state yourself.
P.S. можно по-русски

**Comment by 4external** [comment]
Sorry english guys. 
---
У меня такой сценарий. 
У приложения есть контент для расшаривания, пользователь тапает на ВК-шаринг, например, после первого запуска приложения и в приложении он ещё как аноним, и если не закомментировать строки, то постоянно будет ошибка "access denided. no permissions."
А если закомментировать, то как уже писал - сначала экран от VKSDK что, пользователь не аутентифицирован, затем пользователь входит, и экран шаринга.

**Comment by doomsower** [comment]
Состояние залогинен/незалогинен нужно проверять внутри прилоения соответствующими методами. И разрешения на постинг на стену. По идее можно перед постингом вызвать login с разрешением на постинг на стену. Если залогинен и разрешения есть, то никаких диалогов не будет, и можно вызывать шэринг.

**Comment by doomsower** [comment]
Либо же вызывать логин в обработчике ошибок от шеринга, типа если нет разрешений то просим залогиниться и получить их.

**Comment by 4external** [comment]
А зачем проверять в приложении? А если приложение без пользователей? залогинен/незалогинен пускай смотрит СДК от ВК, наша задача просто вызвать метод СДК на шаринг, а дальше , как в моём случае СДК сам предлагает войти, а потом и шарить.

**Comment by doomsower** [comment]
Потому что это react-native модуль, и весь контроль должен быть на js стороне. Ну и наличие пользователей "в приложении" никак не связано с проверкой залогинен/незалогинен в вк.

В общем-то эту проверку действительно можно убрать, если это поведение по умолчанию от сдк, контролировать со строны js оно не мешает.  Только вот я не уверен в поведении этого sdk. Я смотрю эти обработки разрешений были добавлены отдельным коммитом, сейчас уже не вспомнить зачем, но явно неспроста.

**Comment by MrValyk** [comment]
Всем привет, у меня такой вопрос, 
Приложение на рект-нейтиве под IOS.
при логине и кнопке Разрешить, меня перекидывает в той же вебвью с надписью 
{"error":"invalid_request","error_description":"Security Error"}
указал VKAppId при установке по мануалу, а так же в  Xcode в настройках проекта во вкладке Info-URL_Schema айдишник вида vk0123456, а настройке приложения в вк, указано standalone приложение и  указан boundle id и ios app id. 
Как исправить эту ошибку?

**Comment by andrewkslv** [comment]
@MrValyk где-то ошиблись.
