### ISSUE TITLE
(iOS) authorization on device caused error on allow

### ISSUE THREAD

**Issue by alpamys-qanybet** [doomsower/react-native-vkontakte-login#37]
on iOS 10.0.2 and iOS 11.3, iPhone 5s and X respectively, caused these errors on trying to authorize, both VK is installed and not.

vk is not installed, opened browser.
![aa01](https://user-images.githubusercontent.com/1785462/39121472-2db3e322-470b-11e8-8ac2-52b34c5fcffe.jpg)

vk is installed.
![aa02](https://user-images.githubusercontent.com/1785462/39121474-2dd31a9e-470b-11e8-9da3-24a331fa165e.jpg)

**Comment by doomsower** [comment]
Did you fill in `App Bundle for iOS` in VK app settings? Info [here](https://vk.com/dev/ios_sdk?f=1.%20%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0%20%D0%BA%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E)

**Comment by alpamys-qanybet** [comment]
@doomsower, no, but it has no effect. My application is not published and only available by TestFlight, does it make sense?

**Comment by doomsower** [comment]
This error comes from the wrapper vk-ios-sdk. Usually those errors mean that you haven't configured you app properly (VK APP ID/iOS bundle Id/android fingerprint/url schemas/etc. are wrong). This [issue](https://github.com/VKCOM/vk-ios-sdk/issues/190) shows up when you search for your `error_description` there.

**Comment by alpamys-qanybet** [comment]
@doomsower, It works now, I have discarded my additional properties as first_name, last_name and set the bundle id as you suggested the error is gone. Maybe I need to somehow to compile correctly with my changes to your library, I tried to read about it in your repo, but found nothing.
