### ISSUE TITLE
Проблема при логине из модального окна

### ISSUE THREAD

**Issue by tab** [doomsower/react-native-vkontakte-login#41]
Вход через Вконтакте у меня есть в двух местах: модальное окно входа и экран на котором можно привязать аккаунт Вконтакте. На обычном экране всё работает без проблем, а на экране логина нет.

Компоненты кнопок одинаковые для двух ситуаций:
```
import React, { Component } from "react";
import { connect } from "react-redux";
import { Image, TouchableOpacity, Alert } from "react-native";
import VKLogin from 'react-native-vkontakte-login';

import { loginVkontakte } from "../../../Actions/authActionCreator";
import I18n from '../../../Translations/i18n';
import { VK_APP_ID, VK_APP_PERMISSIONS } from '../../../Config';

class vkLoginButton extends Component {

  componentDidMount() {
    VKLogin.initialize(VK_APP_ID);
  }

  _onCancel = () => {
  }

  _onConfirm = () => {
    const { loginVkontakte } = this.props;
  
    console.log('---confirm---');
 
    VKLogin.login(VK_APP_PERMISSIONS).then((result) => {
      console.log('---result ---');
      console.log(result);

      if (result.email != undefined) {
        loginVkontakte({
          email: result.email,
          token: result.access_token,
          avatar: null,
          name: result.email,
        })
      }
    });
  }

  _onLogin = () => {
    Alert.alert(
      I18n.t('auth.oauth.alert.vk.title'),
      I18n.t('auth.oauth.alert.vk.message'),
      [
        {text: I18n.t('auth.oauth.alert.vk.cancel'), onPress: () => this._onCancel(), style: ''},
        {text: I18n.t('auth.oauth.alert.vk.confirm'), onPress: () => this._onConfirm()},
      ],
      { cancelable: false }
    )
  };

  render() {
    return (
      <TouchableOpacity onPress={this._onLogin}>
        <Image source={require('../../../Images/icons/oauth-vk.png')} />
      </TouchableOpacity>
    );
  }
}

const mapStateToProps = state => ({
});

const mapDispatchToProps = {
  loginVkontakte,
};

const VkLogin = connect(mapStateToProps, mapDispatchToProps)(vkLoginButton);

export default VkLogin;
```

В консоле есть только вывод 
```
---confirm---
```

Если нажать вход на экране привязки, то после этого вход работает и в модальном окне.
И в консоле есть вывод:
```
---confirm---
---result---
{email: 'SECRET', secret: null, user_id: 'SECRET', expires_in: 0, access_token: 'SECRET' }
```

Скорее всего проблема с связана с тем как появляется окно входа через Вконтакте: оно "выезжает справа" (не знаю как это правильно называется) и можно сделать свайп назад.

Для модального окна входа у меня используется 
https://github.com/wix/react-native-navigation
https://wix.github.io/react-native-navigation/#/screen-api?id=showmodalparams-

Можно ли сделать так чтобы окно входа через Вконтакте появлялось в еще одном модальном окне? 
Так сделано в https://github.com/facebook/react-native-fbsdk и с ним проблем нет.

В любом случае буду благодарен за любую помощь.

```
react@16.4.1
react-native@0.56
react-native-vkontakte-login@^0.3.22
react-native-navigation@^1.1.407
react-native-fbsdk@^0.7.0:
```

**Comment by doomsower** [comment]
Это на iOS, на Android или везде?
Я сейчас посмотрел код ios, есть какие-то идеи (заметка - попробовать сделать как в  `[FBSDKInternalUtility topMostViewController]`)
Только сейчас на это нет времени. Может потом выделю время и поковыряю вместе с другими issue этого модуля. Еще поможет репозиторий с минимальным проектом, который воспроизводит этот баг.

**Comment by tab** [comment]
Спасибо за ответ.
На Android пока не проверял, только iOS.
Постараюсь собрать сегодня-завтра минимальный проект с таким поведением.

**Comment by tab** [comment]
@doomsower 

Пример приложения где воспроизводится проблема:
https://github.com/tab/rn-vk-login-modal-example

(wix/react-native-navigation добавил только для iOS, под рукой нет android где можно было бы проверить что всё работает)

**Comment by atlonis** [comment]
@tab получилось решить проблему?

**Comment by doomsower** [comment]
Только что опубликовал `0.4.0-beta.1`. Вроде заработало в демо-приложении выше. Пожалуйста потестируйте.

Для андроида этот баг актуален или нет? При попытке запустить демо-приложение сначала пришлось добавить `gradle-wrapper.jar`, а потом навигация начала жаловаться на иконки и я забил.

**Comment by tab** [comment]
@doomsower 
проверил `0.4.0-beta.1` работает. Спасибо!

Баг на андроид актуален, я поправлю example приложение.

**Comment by tab** [comment]
@doomsower 

Проверил на android – всё работает. Спасибо!
