### ISSUE TITLE
Проблема с разрешением

### ISSUE THREAD

**Issue by azesmway** [doomsower/react-native-vkontakte-login#57]
Приложение добавлено в ВК
iOS bundle и id приложения введены корректно

![Simulator Screen Shot - iPhone Xʀ - 2019-08-10 at 20 19 46](https://user-images.githubusercontent.com/15251391/62824874-376a6780-bbac-11e9-8409-bddaea8ebc8f.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-08-10 at 20 20 11](https://user-images.githubusercontent.com/15251391/62824903-43562980-bbac-11e9-8fd8-06c71db1e76c.png)

Если установлено приложение ВК то через него проходит авторизация а далее выдается ошибка - {"error": "invalid_request", "error_description": "sdk_bundle is incorrect"}

react-native - 0.60.4
react-native-vkontakte-login - 0.4.4

**Comment by doomsower** [comment]
Это значит что неправильно указан **App Bundle ID для iOS** в настройках приложение во вконтакте

**Comment by azesmway** [comment]
> Это значит что неправильно указан **App Bundle ID для iOS** в настройках приложение во вконтакте

<img width="239" alt="image" src="https://user-images.githubusercontent.com/15251391/62825490-3be74e00-bbb5-11e9-9b04-f0594e6bfef4.png">
я указываю тот с которым публикую в апсторе
разве это не он?

**Comment by doomsower** [comment]
Да это он. Эта ошибка приходит от vk-ios-sdk, советую поискать в их репозитории. Скорее всего, что-то где-то неправильно настроено. Может при копировании id случайно проблемы добавились, или url schemes неправильно указаны... Также я никогда не вводил в настройках "App ID для iOS", достаточно было только bundle id.

Очень вряд ли ошибка в этом модуле. Если точно все настроено корректно, можете попробовать в XCode подебагать - я не пробовал с 0.60 react-native еще.

**Comment by azesmway** [comment]
Вроде как победил, но есть проблема - если установлено приложение ВК, то принимает только permissions: 'friends email'. Если его нет, то авторизуется и можно постить на стену. Возник вопрос - а есть ли возможность сделать автопостинг, по событию например или по расписанию ? Без отображения модального окна ВК ?

**Comment by doomsower** [comment]
Не понял в чем проблема? Не получается установить массив прав доступа? Если да, то нужен пример использования и какая ошибка возвращается. Про постинг тоже непонятно. Что конкртено пытаетесь сделать, нужен пример кода.

**Comment by azesmway** [comment]
я хочу сделать пост на свою стену без отображения модального окна ВК
в моем приложении, в бэкграунде запрашиваются новые новости и как только они пришли, я хочу также в бэкграунде их опубликовать у себя на стене

**Comment by azesmway** [comment]
все супер!

вот такой код постит ссылку на стене

`fetchData = async url => {
    return fetch(url)
      .then(jsondata => jsondata.json())
      .catch(error => error)
  }

  postVK = async () => {
    const isLoggedIn = await VKLogin.isLoggedIn()

    if (isLoggedIn) {
      const auth = await VKLogin.getAccessToken()
      const id_app = '<id_app_vk>'
      const link = '<тут ссылка>'
      const attachment = 'photo' + auth.user_id + '_' + id_app + ',' + link
      const url = `https://api.vk.com/method/wall.post?owner_id=${auth.user_id}&attachments=${attachment}&access_token=${
        auth.access_token
      }&v=5.95`
      const data = await this.fetchData(url)
    }
  }`

**Comment by doomsower** [comment]
> еще один отвлеченный вопрос - а ты не разбирался с библиотекой КриптоПро, чтобы ее использовать в React Native ?

нет

**Comment by azesmway** [comment]
а случайно не знаешь, кто может помочь разобраться с их iOS библиотекой?

**Comment by doomsower** [comment]
> а случайно не знаешь, кто может помочь разобраться с их iOS библиотекой?

тоже нет

**Comment by azesmway** [comment]
возможно сможешь подсказать - а подобный постинг на свою стену в фейсбук в бэкграунде возможен? а то я что-то читаю и не пойму, они вроде как закрыли такую возможность и публикация возможно только через их модальное окно

**Comment by FutureOfRussia** [comment]
> Вроде как победил, но есть проблема - если установлено приложение ВК, то принимает только permissions: 'friends email'. Если его нет, то авторизуется и можно постить на стену. Возник вопрос - а есть ли возможность сделать автопостинг, по событию например или по расписанию ? Без отображения модального окна ВК ?

как победил то?

**Comment by khodjaevmsh** [comment]
У меня после входа через ВК (react-native-vkontakte-login), перенаправляет на белый экран. А в console.log() access_token не выводится.

   async function logIn() {
      const isLoggedIn = await VKLogin.isLoggedIn();
      const auth = await VKLogin.login(['friends', 'photos', 'email']);
      console.log(auth.access_token);
      await VKLogin.logout();
    }


  return (
        <View>
            <VKontakte onPress={() => logIn()} />
        </View>
    )
