### ISSUE TITLE
Не закрывается окно авторизации

### ISSUE THREAD

**Issue by Razzze** [doomsower/react-native-vkontakte-login#66]
Добрый день, столкнулся с проблемой при авторизации. 
const auth = await VKLogin.login(['friends', 'photos', 'email']);
При использовании метода login, открывается окно с авторизацией, после чего приложение запрашивает доступ к аккаунта и при нажатии на кнопку разрешить просто происходит открытие этого же окна.

![image](https://user-images.githubusercontent.com/34913304/85158293-17dcaa80-b265-11ea-9d04-06c639e48238.png)

**Comment by Razzze** [comment]
@doomsower

**Comment by doomsower** [comment]
Пример работает? Там есть вариант с friends email photos wall.

Если пример работает, а код нет, то нужен репо с минимальным примером как воспроизвести.

**Comment by Razzze** [comment]
Да действительно, пример работает, проблема была в самом app id.
