### ISSUE TITLE
offline in scope everytime

### ISSUE THREAD

**Issue by vladbars** [doomsower/react-native-vkontakte-login#8]
I call login() method without 'offline' in scope:
VKLogin.login(['friends','photos','audio','video','messages'])
, but in VK says that 'offline' access is required for my app.
Why?

**Comment by vladbars** [comment]
Если по-русски, то зачем он всегда запрашивает бессрочный токен, если я не запрашиваю? )

**Comment by doomsower** [comment]
Это делает SDK Вконтакте
Вот  [Android исходники](https://github.com/VKCOM/vk-android-sdk/blob/3680996ac3709daa816a4d784e090b1a4f184e27/vksdk_library/src/main/java/com/vk/sdk/VKSdk.java#L261), а вот подобный [issue](https://github.com/VKCOM/vk-ios-sdk/issues/243) в ios

**Comment by vladbars** [comment]
так и думал, спасибо

**Comment by vladbars** [comment]
теперь надо думать как его безопасно хранить )
