### ISSUE TITLE
[IOS] При нажатии на кнопку разрешить ничего не происходит

### ISSUE THREAD

**Issue by Kladislav** [doomsower/react-native-vkontakte-login#86]

**Comment by Kladislav** [comment]
До текущего момента либа работала прекрасно, в чем может быть причина?

**Comment by Kladislav** [comment]
@doomsower

**Comment by Kladislav** [comment]
Разобрался, без manual linking больше не работает походу

**Comment by youngblader** [comment]
@Kladislav как решили проблему? https://github.com/doomsower/react-native-vkontakte-login/issues/86

**Comment by Kladislav** [comment]
manual linking, но ещё нашли проблему что авторизация не будет работать если на телефоне установлено приложение vk, по итогу отказались от авторизации через вк:smile:
