### ISSUE TITLE
Already authorized on Android

### ISSUE THREAD

**Issue by vladbars** [doomsower/react-native-vkontakte-login#9]
Once I authorize in iOS - everything is OK, next time when I call login() method, it just returns token,
but on Android it asks access from scope every time!
How make it pass authorization if it was confirmed scope earlier?

по-русски:
На андроиде запрашивает доступ каждый раз при вызове login(), а на iOS как и полагается - если уже разрешал,  сразу отдает токен.

**Comment by doomsower** [comment]
Предполагалось, что это будет использоваться с состоянием, которое определяет, залогинен ли юзер или нет. Поэтому не заметил такой разницы в поведении. Логично ее устранить. Думаю, для этого надо добавить в login проверку как в wakeUpSession из оригинального SDK, только еще как-то scope сверять. 
Постараюсь найти для этого время, а так PR приветствуется.

**Comment by vladbars** [comment]
Ну да, если scope не меняется - отдавать токен просто. 
Спасибо.

**Comment by doomsower** [comment]
Closed in 77e5a3db83131db00ca90dec78981abcc3f62ea9
